name: monarch
description: Code generator for Monarch. Monarch is a tool for building Flutter widgets in isolation. It makes it easy to build, test and debug complex UIs.
version: 3.10.0
homepage: https://monarchapp.io
repository: https://github.com/Dropsource/monarch
issue_tracker: https://github.com/Dropsource/monarch/issues
documentation: https://monarchapp.io/docs/introduction
topics:
  - tool
  - ui
  - monarch
  - stories

screenshots:
  - description: Write stories to isolate your widgets. Then preview stories without running your app or backend.
    path: screenshots/01-stories-fs8.png
  - description: See your widgets in different modes. Make sure your UI works across multiple devices, text scales, languages, and themes.
    path: screenshots/02-devices-fs8.png
  - description: Debug widgets in isolation. Fine-tune animations, fix layout issues, align text. Find images using too much memory.
    path: screenshots/03-debug-fs8.png
  - description: Find and fix bugs with ease. Stories render edge cases with little effort.
    path: screenshots/04-find-bugs-fs8.png

environment:
  sdk: ^3.7.0
  flutter: '>=3.38.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  build: ^4.0.0
  source_gen: ^4.0.0
  dart_style: ^3.0.1
  monarch_definitions: ^1.7.0
  monarch_annotations: ^1.1.0
  monarch_utils: ^1.2.0
  glob: ^2.0.1
  analyzer: '>=8.1.1 <11.0.0'
  path: ^1.8.0
  vm_service: '>=9.4.0 <16.0.0'
  meta: ^1.3.0
  stack_trace: ^1.10.0
  flutter_test:
    sdk: flutter

dev_dependencies: 
  lints: ^5.1.1

flutter:

