name: monarch_controller
description: Monarch Controller UI
publish_to: 'none'
version: 1.5.1

environment:
  sdk: ^3.2.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  rxdart: ^0.28.0
  flutter_localizations:
    sdk: flutter
  intl: any
  monarch_annotations: ^1.1.0
  monarch_definitions: ^1.7.0
  monarch_io_utils: ^1.4.0
  monarch_utils: ^1.2.0
  grpc: ^4.0.1
  monarch_grpc: ^2.4.0
  stockholm:
    git:
      url: https://github.com/Dropsource/monarch_stockholm/
      ref: monarch_stockholm-1.0.0
  syncfusion_flutter_core: ^28.2.9
  syncfusion_flutter_sliders: ^28.2.9
  rive: ^0.14.0

dev_dependencies:
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  monarch: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - locale/i18n_en.json
    - locale/i18n_es.json
